---
title: "accessory gland model: technical details"
date: "`r format(Sys.Date(), '%d %B %Y')`"
author: "Ben Bolker and Lucas Eckert"
bibliography: corHMM.bib
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    number_sections: true	

---

<!-- **fix me**: reimplement as [target markdown](https://books.ropensci.org/targets/markdown.html#markdown) ? -->

```{r setup, message=FALSE}
source("R/utils.R")
source("R/mcmc.R")
source("R/functions.R")
load_pkgs()
zmargin <- theme(panel.spacing = grid::unit(0, "lines"))
theme_set(theme_bw())
library(targets)
```

<!-- to suppress tidyverse messages, need callr_function = NULL *or* some other shenanigans -->

# Workflow

using `targets` package

```{r visnetwork, message=FALSE, echo = FALSE, eval = FALSE}
tar_visnetwork(targets_only = TRUE)
```

# Maximum likelihood estimation

Uses an enhanced version of the `corHMM` package. Additions:

- accessor methods, for convenience
   - `coef()` (coefficients)
   - blah

# Contrasts

\[
\begin{split}
p_c & = C p \\
\Sigma(p_c) & = C_p^{\top} \Sigma(p) C_p
\end{split}
\]

# Markov chain Monte Carlo

- Trace plots and pair plots of posterior distributions
