---
title: "pagelComparison"
output: html_document
---

```{r}
source("R/utils.R")
source("R/mcmc.R")
source("R/functions.R")
load_pkgs()
zmargin <- theme(panel.spacing = grid::unit(0, "lines"))
theme_set(theme_bw())
```

```{r}
data(primates)
phy <- multi2di(primates[[1]])
data <- primates[[2]]
```

```{r statemat}
LegendAndRateMat <- getStateMat4Dat(data)
LegendAndRateMat$legend<-c("0_0","0_1","1_0","1_1")
names(LegendAndRateMat$legend)<-c(1,2,3,4)
LegendAndRateMat$rate.mat<- matrix(c(0,1,2,0,3,0,0,4,5,0,0,6,0,7,8,0), nrow = 4, dimnames = list(c("(1)","(2)","(3)","(4)"), c("(1)","(2)","(3)","(4)")))
RateMat <- LegendAndRateMat$rate.mat
```

```{r ex1,cache=TRUE}
(MK_primate_full <- corHMM(phy = phy, data = data, rate.cat = 1, collapse = FALSE, rate.mat = RateMat))
print(MK_primate_full)
```

```{r}
#primate_mcmc <- 
  corhmm_mcmc(MK_primate_full,
              p_args=list(nllfun=make_nllfun(MK_primate_full)),
              ncores = 3,
              nchains = 6,
              ## these are per chain
              n_burnin = 4000,
              n_iter = 44000,
              thin = 10,
              seed = 101)
#saveRDS(primate_mcmc, file = "primateMCMC.rds")

primate_mcmc<-readRDS("primateMCMC.rds")
## reset parameter names so we can see the trace plot
## more easily
primate_mcmc[] <- lapply(primate_mcmc,
                       function(x) { 
                         colnames(x) <- c("q21", "q31", "q12", "q42",
                                          "q13", "q43", "q24", "q34")
                         return(x)
                       })
lattice::xyplot(primate_mcmc, layout=c(2,4), aspect="fill",
                as.table = TRUE)
```

```{r}
m1 <- as.mcmc(primate_mcmc)
## q12 <- m1[,3]
## q21 <- m1[,1]
## q13 <- m1[,5]
## q31 <- m1[,2]
## q24 <- m1[,7]
## q42 <- m1[,4]
## q34 <- m1[,8]
## q43 <- m1[,6]

df <- (as.data.frame(m1)
  %>% pivot_longer(everything(), names_to="var", values_to = "logval")
  %>% mutate(value = exp(logval))
)

ggplot(df, aes(x=value)) + facet_wrap(~var, nrow = 2, scales="free") +
  geom_histogram(breaks = seq(0,1, by = 0.01))

ggplot(df, aes(x=logval)) + facet_wrap(~var, nrow = 2) +
  geom_histogram(bins = 50)

ggplot(df, aes(x=logval)) + facet_wrap(~var, nrow = 2) +
  geom_density(fill="gray")

ggplot(df, aes(x=value)) + facet_wrap(~var, nrow = 2, scales="free") +
  geom_density(fill="gray")

df %>% group_by(var) %>% summarise(across(c(logval, value),
                                   list(min=min, max=max)))

```
