---
title: "Two Trait Model"
output: html_document
---

```{r}
source("R/utils.R")
source("R/mcmc.R")
source("R/functions.R")
load_pkgs()
zmargin <- theme(panel.spacing = grid::unit(0, "lines"))
theme_set(theme_bw())
```

```{r}
allData <- read.csv("data/binaryTraitData.csv", header = TRUE)
traitData <- with(allData,
                  data.frame(species, ag, care, names=species))
fullPhy <- suppressWarnings(fishtree_phylogeny(traitData$species)) ## request 607, only find 478 spp
trimmedData <- comparative.data(fullPhy, traitData, names.col = names)
phy <- trimmedData$phy
data <- trimmedData$data
getStateMat4Dat(data)
```

```{r}
LegendAndRateMat <- getStateMat4Dat(data)
RateMat <- LegendAndRateMat$rate.mat
pars2equal <- list(c(3,8), c(5,7), c(1,6), c(2,4))
print(indStateMat <- equateStateMatPars(RateMat, pars2equal))
indModel<- corHMM(phy = phy, data = data, rate.cat = 1, root.p = c(1,0,0,0), rate.mat = indStateMat)
print(indModel)
```

```{r}
depModel<- corHMM(phy = phy, data = data, rate.cat = 1, root.p = c(1,0,0,0))
print(depModel)
```

```{r}
#likelihood ratio test, same as Pagel's test of correlated evolution used in my thesis
print(likRatio<- -2*(indModel$loglik-depModel$loglik))
print(p.val <- pchisq(likRatio, df = 4, lower.tail = F))
#my thesis found a p value of < 0.001 so this is good so far
```

```{r}
# ind_twoTrait_mcmc <- 
#   corhmm_mcmc(indModel,
#               p_args=list(nllfun=make_nllfun(indModel)),
#               n_cores = 3,
#               n_chains = 6,
#               ## these are per chain
#               n_burnin = 4000,
#               n_iter = 44000,
#               n_thin = 10,
#               seed = 101)
# saveRDS(ind_twoTrait_mcmc, file = "indTwoTraitMCMC.rds")
```

```{r}
# dep_twoTrait_mcmc <- 
#   corhmm_mcmc(depModel,
#               p_args=list(nllfun=make_nllfun(depModel)),
#               n_cores = 3,
#               n_chains = 6,
#               ## these are per chain
#               n_burnin = 4000,
#               n_iter = 44000,
#               n_thin = 10,
#               seed = 101)
# saveRDS(dep_twoTrait_mcmc, file = "depTwoTraitMCMC.rds")
```

```{r}
dep_mcmc<-readRDS("depTwoTraitMCMC.rds")
lattice::xyplot(dep_mcmc, layout=c(2,4), aspect="fill",
                as.table = TRUE)
```

```{r}
dep_mcmc[] <- lapply(dep_mcmc,
                       function(x) { 
                         colnames(x) <- c("q21", "q31", "q12", "q42",
                                          "q13", "q43", "q24", "q34")
                         return(x)
                       })

m1 <- as.mcmc(dep_mcmc)

df <- (as.data.frame(m1)
  %>% pivot_longer(everything(), names_to="var", values_to = "logval")
  %>% mutate(value = exp(logval))
)
ggplot(df, aes(x=value)) + facet_wrap(~var, nrow = 2, scales="free") +
  geom_histogram(bins = 100)

summary(m1)
```
